export const details = [
  {
    images: '../../assets/images/frontend-project.png',
    vercel: 'https://project-frontend-amber.vercel.app/',
    github: 'https://github.com/nikosBatzonis/Project-Frontend',
    skills: 'HTML5, CSS, Bootstrap 5, TS, Angular',
    them: 'Team Project',
    more: 'We worked on a project in a team of four. Using a brainstorming design approach, Miro Planning Board and Kanban Task Management for efficient teamwork. We finished the site in 3 1/2 days.',
  },
  {
    images: '../../assets/images/cr6.png',
    vercel: 'https://fe-21-cr-6-nikos-batzonis.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-CR6-nikosBatzonis',
    skills: 'HTML5, CSS, Bootstrap 5, TS, Angular',
    them: 'CodeReview 6',
    more: 'The focus of this Code Review was to create a travel page with interactive cart functionality by using the Angular ngFor feature.',
  },
  {
    images: '../../assets/images/petstore.png',
    vercel: 'https://fe-21-angular-day-3-nikolaos-aaron.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-Angular-DAY3-Nikolaos-Aaron',
    skills: 'HTML5, SASS, Bootstrap 5, TS, Angular',
    them: 'Petstore',
    more: '',
  },
  {
    images: '../../assets/images/car-rent.png',
    vercel: 'https://fe-21-angular-day-2-nikolaos.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-Angular-DAY2-nikolaos',
    skills: 'HTML5, SASS, Bootstrap 5, TS, Angular',
    them: 'Car rent',
    more: '',
  },
  {
    images: '../../assets/images/cr5.png',
    vercel: 'https://fe-21-cr-5-nikos-batzonis.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-CR5-nikosBatzonis',
    skills: 'HTML5, SASS, Bootstrap 5, TS',
    them: 'CodeReview 5',
    more: 'Code Review 05 was about creating a travel blog page that utilizes dynamic page generation and manipulation of the DOM by adding a sort feature (ascending and descending order by date).',
  },
  {
    images: '../../assets/images/cr4.png',
    vercel: 'https://fe-21-cr-4-nikos-batzonis.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-CR4-nikosBatzonis',
    skills: 'HTML5, SASS, Bootstrap 5, JS, Json',
    them: 'CodeReview 4',
    more: 'In this Code Review we focused on generating a page dynamically from a .json file and adding a like button with a sort function to sort the movies by number of likes.',
  },
  {
    images: '../../assets/images/flower.png',
    vercel: 'https://fe-21-js-day-8-nikolaos.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-JS-DAY8-Nikolaos-Uros',
    skills: 'HTML5, CSS, Bootstrap 5, JS',
    them: 'Flowers',
    more: '',
  },
  {
    images: '../../assets/images/cr3.png',
    vercel: 'https://fe-21-cr-3-nikos-batzonis.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-CR3-nikosBatzonis',
    skills: 'HTML5, SASS, JS, Bootstrap 5',
    them: 'CodeReview 3',
    more: 'This Code Review was about applying our knowledge of Bootstrap 5, Sass and to just create the first JavaScript calculations and to get familiar with the console.',
  },
  {
    images: '../../assets/images/cr2.png',
    vercel: 'https://fe-21-cr-2-nikos-batzonis.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-CR2-nikosBatzonis',
    skills: 'HTML5, SASS, flex',
    them: 'CodeReview 2',
    more: 'In this Code Review I created a news blog and the focus was to get familiar with dynamic pages and video integration by using Sass and HTML.',
  },
  {
    images: '../../assets/images/cr1.png',
    vercel: 'https://fe-21-cr-01-nikos-batzonis.vercel.app/',
    github: 'https://github.com/nikosBatzonis/FE21-CR01-nikosBatzonis',
    skills: 'HTML5, CSS',
    them: 'CodeReview 1',
    more: 'This was my first Code Review and I got familiar with the DOM and basic CSS properties.',
  },
  {
    images: '../../assets/images/testimonial.png',
    vercel: 'https://testimonials-grid-section-main-eight-dun.vercel.app/',
    github: 'https://github.com/nikosBatzonis/grid-testimonials-section-main',
    skills: 'HTML5, CSS, Grid',
    them: 'Testimonials',
    more: '',
  },
  {
    images: '../../assets/images/journey.png',
    vercel: 'https://journey-to-world-web-page.vercel.app/',
    github: 'https://github.com/nikosBatzonis/-Journey-to-World',
    skills: 'HTML5, CSS, Grid, flex',
    them: 'Journey to world',
    more: '',
  },
  {
    images: '../../assets/images/social-proof.png',
    vercel: 'https://social-proof-section-master-ashy.vercel.app/',
    github: 'https://github.com/nikosBatzonis/social-proof-section-master',
    skills: 'HTML5, CSS, flex',
    them: 'Social proof',
    more: '',
  },
  {
    images: '../../assets/images/citrus.png',
    vercel: 'https://citrus.vercel.app/',
    github: 'https://github.com/nikosBatzonis/Citrus',
    skills: 'HTML5, CSS, flex',
    them: 'Citrus',
    more: '',
  },
  {
    images: '../../assets/images/chat-app.png',
    vercel: 'https://citrus.vercel.app/',
    github: 'https://github.com/nikosBatzonis/chat-app-css-illustration-master',
    skills: 'HTML5, CSS, flex',
    them: 'Chat app',
    more: '',
  },
  {
    images: '../../assets/images/sky.png',
    vercel: 'https://sky-tan.vercel.app/',
    github: 'https://github.com/nikosBatzonis/Sky',
    skills: 'HTML5, CSS, flex',
    them: 'Sky',
    more: '',
  },
  {
    images: '../../assets/images/four-card.png',
    vercel: 'https://four-card-feature-section-master-one-alpha.vercel.app/',
    github:
      'https://github.com/nikosBatzonis/four-card-feature-section-master-',
    skills: 'HTML5, CSS',
    them: 'Four card',
    more: '',
  },
];
